### ISSUE TITLE
ColorProperty seems to not exist

### ISSUE THREAD

**Issue by rgommers** [Solder-Soldier/Test#1]
On line 21 of ``RingDig2.py``. Running the current version of the app on OS X gives:

   ----> 1 from kivy.properties import ColorProperty

    ImportError: cannot import name 'ColorProperty'

I also cannot find ``ColorProperty`` in the docs or with a Google search.

**Comment by Solder-Soldier** [comment]
![image](https://cloud.githubusercontent.com/assets/24915363/24015231/bbbad1d2-0aec-11e7-9d7b-e8c5aae8cfde.png)

This screenshot shows the ColorProperty in kivy.properties in Kivy v1.9.2. 

Could it be that you are running an older version of Kivy. ColorProperty I think is quite new...

![image](https://cloud.githubusercontent.com/assets/24915363/24015419/4aafbd26-0aed-11e7-9796-070acf1272aa.png)

**Comment by rgommers** [comment]
Thanks, got it.

For future reference, this was introduced in 1.9.2 (which is not released yet).
